---
abstract: 'Binary Search within a sorted array.'
author:
  - 'David Oswald <davido [@at] cpan [d.o.t] org>'
build_requires:
  English: 0
  Test::More: 0.98
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-BinarySearch
no_index:
  directory:
    - t
    - inc
provides:
  List::BinarySearch:
    file: lib/List/BinarySearch.pm
    version: 0.16
  List::BinarySearch::PP:
    file: lib/List/BinarySearch/PP.pm
    version: 0.16
recommends:
  List::BinarySearch::XS: 0.05
requires:
  Scalar::Util: 0
  perl: 5.008000
resources:
  repository: https://github.com/daoswald/List-BinarySearch.git
version: 0.17
