---
abstract: 'Binary Search a sorted list or array.'
author:
  - 'David Oswald <davido [@at] cpan [d.o.t] org>'
build_requires:
  English: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.62
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-BinarySearch
no_index:
  directory:
    - t
    - inc
provides:
  List::BinarySearch:
    file: lib/List/BinarySearch.pm
    version: 0.11
requires:
  Scalar::Util: 0
  perl: 5.006000
version: 0.11
