---
abstract: 'Binary Search a sorted list or array.'
author:
  - 'David Oswald <davido@cpan.org>'
build_requires:
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-BinarySearch
no_index:
  directory:
    - t
    - inc
requires:
  Scalar::Util: 0
version: 0.05
